sudo: false

language: php

dist: trusty

php:
  - "7.1"
  - "7.0"
  - "5.6"
  - "5.5"
  - "5.4"
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: nightly
  include:
    - php: "5.3"
      dist: precise

before_script:
  - composer update --no-interaction
  
script:
  - phpunit --bootstrap ./tests/bootstrap.php -c tests/phpunit.xml --coverage-clover build/logs/clover.xml tests
  
after_script:
  - php ./vendor/bin/coveralls -v
